# Generated by Django 3.0.11 on 2020-11-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ipam', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '客户线路', 'verbose_name_plural': '客户线路表'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ipam.Product'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='subnet_class',
            field=models.CharField(blank=True, choices=[('BGP', 'BGP'), ('CT', '电信'), ('CU', '联通'), ('CM', '移动')], max_length=10, verbose_name='IP分类'),
        ),
    ]
